//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentList
    {
        public int IDEqList { get; set; }
        public int IDModelList { get; set; }
        public int IDEquipment { get; set; }
        public System.DateTime DateShiping { get; set; }
        public Nullable<System.DateTime> DateReturning { get; set; }
        public bool IsReturned { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual ModelList ModelList { get; set; }
    }
}
