//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogisticsEntities : DbContext
    {
        public LogisticsEntities()
            : base("name=LogisticsEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentList> EquipmentList { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<ModelList> ModelList { get; set; }
        public virtual DbSet<Rents> Rents { get; set; }
        public virtual DbSet<TransferEquipment> TransferEquipment { get; set; }
        public virtual DbSet<ReportMessage> ReportMessage { get; set; }
    }
}
