//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int idManager { get; set; }
        public string family { get; set; }
        public string name { get; set; }
        public string post { get; set; }
        public string password { get; set; }
        public string Location { get; set; }
    }
}
